### ISSUE TITLE
missing files from train/test/dev lists

### ISSUE THREAD

**Issue by aminianmary** [propbank/propbank-release#2]
Hi,
Some of the files that are listed in the standard train/test/dev lists (in docs/evaluation directory) are not in the respective directories. As an example "ontonotes/wb/sel/09/sel_0960" from the ontonotes dev list is not located there.
Are some of the files omitted from this list?
--Thanks
Maryam

**Comment by timjogorman** [comment]
When a file in the data doesn't have any predicates associated with it, our current pipeline simply omits it (that's the case with sel_0960).  For most tasks, I presume that this doesn't matter, but we can provide gold_skel files for these empty files in the next release.

**Comment by aminianmary** [comment]
Thanks for your reply.
I double checked sel_0960 in Ontonotes and it contains this sentence: 

> "if your housting package provides python it should "support" at least some frameworks and give some help about setting up them...". 

which has predicates. Is predicate id done automatically?
Thanks

**Comment by timjogorman** [comment]
The "sel" data in ontonotes is the only part of the "Propbank " data I know of without full verbal coverage -- I believe it was selected during active learning experiments, and annotation originally only covered verbal senses being studied.  Those file progress alphabetically in terms of what is being analyzed; "sel/09" files seem generally to be selected for "get"; those in "sel/08" for "fall" and "fly", "sel/10" for  "handle" and "kill", etc.   Some later passes added additional annotations (e.g. some nominal and light verb annotations), but we haven't gone back and gotten full verbal coverage over that data. We'd probably be happy to, if a group were to fund that. 

Normal Propbank IS done with automatic predicate ID, but it's done with a focus on high recall; annotators are given all verbs (based upon the gold LDC trees) and, for more recent data, all copular adjectives and predicative nouns (allowing annotators to mark things as non-predicative, which are then not released in the data).  So outside of that "wb/sel" data, there should be pretty consistent verbal coverage.

**Comment by aminianmary** [comment]
Thanks Tim!
