### ISSUE TITLE
Difference between LDC Treebanks and this repository

### ISSUE THREAD

**Issue by arademaker** [propbank/propbank-release#5]
In the https://catalog.ldc.upenn.edu/LDC2012T13 we only have syntactic analysis. But https://catalog.ldc.upenn.edu/LDC2013T19 have already predicate-argument structures.  What is the difference between the Ontonotes data here and the predicate-argument structures from the treebank in LDC?

In https://github.com/propbank/propbank-release#how-does-this-relate-to-prior-ontonotes-releases, it says that this repo is only a subset of the annotations of the LDC data plus the change on the way to handle disfluencies, is that right? So we don't have improvements on the annotations of predicates and arguments?

**Comment by timjogorman** [comment]
> In the https://catalog.ldc.upenn.edu/LDC2012T13 we only have syntactic analysis. But https://catalog.ldc.upenn.edu/LDC2013T19 have already predicate-argument structures. What is the difference between the Ontonotes data here and the predicate-argument structures from the treebank in LDC?

The data here is different from (and meant to replace) the PropBank data released in the LDC2013T19 Ontonotes package.   We added more annotations, and it is an updated version of the lexicon that has a bunch of annotations in the new "unified" format. 

> https://github.com/propbank/propbank-release#how-does-this-relate-to-prior-ontonotes-releases, it says that this repo is only a subset of the annotations of the LDC data plus the change on the way to handle disfluencies, is that right? So we don't have improvements on the annotations of predicates and arguments?

There *are* improvements to the OntoNotes SRL annotations, as stated above.  That section was just saying that we didn't re-release non-SRL annotations (like coreference) here.  For more details on the changes to the SRL data, see the [Unified Propbank LREC paper](https://www.aclweb.org/anthology/L18-1231/)
